CREATE TABLE department (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code        VARCHAR(20)  NOT NULL UNIQUE,
    name        VARCHAR(100) NOT NULL UNIQUE,
    location    VARCHAR(100),
    manager_id  BIGINT,
    created_at  TIMESTAMP    NOT NULL,
    updated_at  TIMESTAMP    NOT NULL
);

CREATE TABLE employee (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name    VARCHAR(50)    NOT NULL,
    last_name     VARCHAR(50)    NOT NULL,
    email         VARCHAR(120)   NOT NULL UNIQUE,
    job_title     VARCHAR(80)    NOT NULL,
    salary        DECIMAL(12, 2) NOT NULL CHECK (salary > 0),
    hire_date     DATE           NOT NULL,
    status        VARCHAR(20)    NOT NULL,
    department_id BIGINT REFERENCES department (id),
    version       BIGINT         NOT NULL DEFAULT 0,
    created_at    TIMESTAMP      NOT NULL,
    updated_at    TIMESTAMP      NOT NULL
);

ALTER TABLE department
    ADD CONSTRAINT fk_department_manager FOREIGN KEY (manager_id) REFERENCES employee (id);

CREATE INDEX idx_employee_department ON employee (department_id);
CREATE INDEX idx_employee_last_name ON employee (last_name);
